Various Improvements

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -1,27 +1,40 @@
 #!/bin/sh
 set -e
 
-RPI_IP=@RPI_IP@
-RPI_USER=@RPI_USER@
-RPI_DIR=@RPI_DIR@
+RPI_IP="@RPI_IP@"
+RPI_USER="@RPI_USER@"
+RPI_DIR="@RPI_DIR@"
+
+EXE_PATH=$1
+EXE_NAME=$2
 
 echo "\e[1;36m[i] Installing to RasPi..."
 
-if [ ! -f $1 ]; then
+if [ ! -f "$EXE_PATH/$EXE_NAME" ]; then
     echo "\e[1;31m[X] Executable not found!\e[0m"
     return 1
 fi
 
+echo "\e[1;36m[i] Checking for RasPi..."
 ping -c1 $RPI_IP >/dev/null 2>&1 || {
     echo "\e[1;31m[X] RasPi not found!\e[0m"
     return 1
 }
+echo "\e[1;32m[+] RasPi found!\e[0m"
 
 echo "\e[1;36m[i] Copying to RasPi..."
-
-scp -r $1 $RPI_USER@$RPI_IP:$RPI_DIR >/dev/null 2>&1 || {
-    echo -e "\e[1;31m[X] Copy failed!\e[0m"
+scp -r "$EXE_PATH/$EXE_NAME" $RPI_USER@$RPI_IP:$RPI_DIR >/dev/null 2>&1 || {
+    echo "\e[1;31m[X] Copy failed!\e[0m"
     return 1
 }
 echo "\e[1;32m[+] Copy successful!\e[0m"
+
+echo "\e[1;36m[i] Setting permissions..."
+ssh $RPI_USER@$RPI_IP "chmod +x $RPI_DIR/$EXE_NAME" >/dev/null 2>&1 || {
+    echo "\e[1;31m[X] Setting permissions failed!\e[0m"
+    return 1
+}
+echo "\e[1;32m[+] Setting permissions successful!\e[0m"
+
+echo "\e[1;32m[+] Installation successful!\e[0m"
 return 0
